config/routes.rb
Rails.application.routes.draw do
root 'abouts#index'
 resources :abouts
end

app/models/about.rb
class About < ApplicationRecord
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
    def index
        @about = About.all 
    end

    def new 
        @about = About.new
    end

    def create
        About.create(about_params)
        redirect_to root_path
      end
    
      private
    
      def about_params
        params.require(:about).permit(:name,:year, :description)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abouts/index.html.erb
<div class="box col-sm-3 offset-1">
<h1>Welcome to My New Web app</h1>


<%= link_to 'Enter you Favor Movie', new_about_path, class: "links"  %>


<% @about.each do |about| %>
  <div>
    <h2><%= about.name %></h2><br />
    <i><%= about.year %></i><br />
    <br />
    <p><%= about.description %></p><br />
  </div>
  <% end %>
</div>

app/views/abouts/new.html.erb
<div class="booyah-box col-5 offset-3">
<h1>Enter Your Own favorite Movie</h1>

<%= simple_form_for @about do |f| %>
  <%= f.input :name %>
  <%= f.input :year %>
  <%= f.input :description %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
  <%= link_to 'back to home page', root_path  %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tester</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Tester</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
  </div>
</nav>

<br />
    <%= yield %>
  </body>
</html>